#!/usr/bin/env ruby
# Compile and upload content

UPLOAD_TO = 'rubyforge.org:/var/www/gforge-projects/r18n/'
LOGIN = ARGV.first

unless LOGIN
  puts 'Error: Please, set your RubyForge login in first argument.'
  exit
end

require 'pathname'
load Pathname.new(__FILE__).dirname.join('build')

exec "rsync --recursive --delete --compress --progress --human-readable #{PUBLIC}/ #{LOGIN}@#{UPLOAD_TO}"
