.ruby: &ruby
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $CIRRUS_OS
      - ruby -v
      - cat Gemfile
  install_script:
    - bundle update

remark_task:
  container:
    image: node:latest
  node_modules_cache:
    folder: node_modules
    fingerprint_script:
      - echo $CIRRUS_OS
      - node -v
      - cat package.json
    populate_script: npm install
  remark_script: npm run remark

rubocop_task:
  <<: *ruby
  container:
    image: ruby:latest
  rubocop_script: bundle exec rubocop
