ok: 'Сайн'
save: 'Хадгал'
cancel: 'Цуцлах'
'yes': 'Тийм'
'no': 'Үгүй'
exit: 'Гарц'
delete: 'Устга'

human_time:
  after_days: '%1 Өдрийн дараа'
  tomorrow: 'Маргааш'
  after_hours: '%1 Цагийн дараа'
  after_minutes: '%1 Минутны дараа'
  now: 'Одоо'
  today: 'Өнөөдөр'
  minutes_ago: '%1 Минутны өмнө'
  hours_ago: '%1 Цагийн өмнө'
  yesterday: 'Өчигдөр'
  days_ago: '%1 Өдрийн өмнө'
