# encoding: utf-8

require 'rubygems'

begin
  require 'bundler/setup'
  Bundler::GemHelper.install_tasks
rescue LoadError
  puts "Bundler not available. Install it with: gem install bundler"
end

PKG_NAME = 'r18n-core'.freeze
require File.join(File.dirname(__FILE__), 'lib/r18n-core/version')

require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new

task :spec_syck do
  ENV['test_syck'] = '1'
  sh "#{RUBY} -S rake spec", :verbose => false
end

require 'yard'
YARD::Rake::YardocTask.new do |yard|
  yard.options << "--title='R18n #{R18n::VERSION}'"
end

task :clobber_doc do
  rm_r 'doc'     rescue nil
  rm_r '.yardoc' rescue nil
end
task :clobber_package do
  rm_r 'pkg' rescue nil
end
task :clobber => [:clobber_package, :clobber_doc]

task :default => :spec
