# encoding: utf-8
require 'rubygems'
require 'rake/gempackagetask'
gem 'rspec'
require 'spec/rake/spectask'
begin
  require 'hanna/rdoctask'
rescue LoadError
  require 'rake/rdoctask'
end

PKG_NAME = 'r18n-desktop'
require '../r18n-core/lib/r18n-core/version'

task :default => :spec

Spec::Rake::SpecTask.new('spec') do |t|
  t.libs << '../r18n-core/lib'
  t.spec_opts = ['--format', 'specdoc', '--colour']
  t.spec_files = Dir['spec/**/*_spec.rb'].sort
end

Rake::RDocTask.new do |rdoc|
  rdoc.main = 'README.rdoc'
  rdoc.rdoc_files.include('README.rdoc', 'LICENSE', 'lib/**/*.rb')
  rdoc.title = 'R18n Desktop Documentation'
  rdoc.rdoc_dir = 'doc'
  rdoc.options << '-c utf-8'
  rdoc.options << '--all'
end

spec = eval(File.read('r18n-desktop.gemspec'))
Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

desc 'Install as a gem'
task :install => [:package] do
  sudo = RUBY_PLATFORM =~ /win32/ ? '' : 'sudo'
  sh %{#{sudo} gem install pkg/#{PKG_NAME}-#{R18n::VERSION}}
end
