source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'sqlite3'

# Bundle the extra gems:
gem 'r18n-rails', :path => '../..'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  gem 'rspec-core'
  gem 'rspec-expectations'
  gem 'rspec-mocks'
end
