# encoding: utf-8
require 'rubygems'
require 'rake/rdoctask'
require 'rake/gempackagetask'
gem 'rspec'
require 'spec/rake/spectask'

PKG_NAME = 'sinatra-r18n'
require '../r18n-core/lib/r18n-core/version'

task :default => :spec

Spec::Rake::SpecTask.new('spec') do |t|
  t.libs << '../r18n-core/lib'
  t.spec_opts = ['--format', 'specdoc', '--colour']
  t.spec_files = Dir['spec/**/*_spec.rb'].sort
end

Spec::Rake::SpecTask.new('rcov') do |t|
  t.libs << '../r18n-core/lib'
  t.spec_opts = ['--colour']
  t.spec_files = Dir['spec/**/*_spec.rb'].sort
  t.rcov = true
  t.rcov_opts = ['--text-summary']
end

Rake::RDocTask.new do |rdoc|
  rdoc.main = 'README.rdoc'
  rdoc.rdoc_files.include('README.rdoc', 'LICENSE', 'lib/**/*.rb')
  rdoc.title = 'Sinatra R18n Documentation'
  rdoc.rdoc_dir = 'doc'
  rdoc.options << '-c utf-8'
  rdoc.options << '--all'
end

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.name = PKG_NAME
  s.version = R18n::VERSION
  s.summary = 'A Sinatra extension that provides i18n support to translate your
    web application.'
  s.description = <<-EOF
    A Sinatra extension that provides i18n support to  translate your web
    application. It is just a wrap for R18n core library.
    It can format numbers and time to the rules of the user locale,
    has translation for common words, storage translation in YAML format with
    pluralization, procedures and user filters and has special support for
    countries with two official languages.
  EOF
  
  s.files = FileList[
    'lib/**/*',
    'LICENSE',
    'README.rdoc']
  s.test_files = FileList[
    'spec/**/*']
  s.extra_rdoc_files = ['README.rdoc', 'LICENSE']
  s.require_path = 'lib'
  s.has_rdoc = true
  
  s.add_dependency 'r18n-core', R18n::VERSION
  
  s.author = 'Andrey "A.I." Sitnik'
  s.email = 'andrey@sitnik.ru'
  s.homepage = 'http://r18n.rubyforge.org/'
  s.rubyforge_project = PKG_NAME
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

desc 'Install as a gem'
task :install => [:package] do
  sudo = RUBY_PLATFORM =~ /win32/ ? '' : 'sudo'
  sh %{#{sudo} gem install pkg/#{PKG_NAME}-#{R18n::VERSION}}
end
