# encoding: utf-8

require 'rubygems'

begin
  require 'bundler/setup'
  Bundler::GemHelper.install_tasks
rescue LoadError
  puts "Bundler not available. Install it with: gem install bundler"
end

PKG_NAME = 'sinatra-r18n'
require '../r18n-core/lib/r18n-core/version'

require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new

require 'yard'
YARD::Rake::YardocTask.new do |yard|
  yard.options << "--title='Sinatra R18n #{R18n::VERSION}'"
end

task :clobber_package do
  rm_r 'pkg' rescue nil
end
task :clobber => [:clobber_package]

task :default => :spec
