# encoding: utf-8
require 'rubygems'

begin
  require 'bundler/setup'
  Bundler::GemHelper.install_tasks
rescue LoadError
  puts "Bundler not available. Install it with: gem install bundler"
end

PKG_NAME = 'r18n-rails'
require '../r18n-core/lib/r18n-core/version'

require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new

require 'yard'
YARD::Rake::YardocTask.new do |yard|
  yard.options << "--title='R18n for Rails #{R18n::VERSION}'"
end

task :clobber_doc do
  rm_r 'doc' rescue nil
end
task :clobber_package do
  rm_r 'pkg' rescue nil
end
task :clobber => [:clobber_package, :clobber_doc]

task :default => :spec
