# encoding: utf-8
require 'rubygems'

begin
  require 'bundler'
  Bundler::GemHelper.install_tasks
rescue LoadError
  puts "Bundler not available. Install it with: gem install bundler"
end

require 'spec/rake/spectask'
begin
  require 'hanna/rdoctask'
rescue LoadError
  require 'rake/rdoctask'
end

PKG_NAME = 'r18n-rails'
require '../r18n-core/lib/r18n-core/version'

task :default => :spec

Spec::Rake::SpecTask.new('spec') do |t|
  t.libs << '../r18n-core/lib'
  t.libs << '../r18n-rails-api/lib'
  t.spec_opts = ['--format', 'specdoc', '--colour']
  t.spec_files = Dir['spec/**/*_spec.rb'].sort
end

Rake::RDocTask.new do |rdoc|
  rdoc.main = 'README.rdoc'
  rdoc.rdoc_files.include('README.rdoc', 'LICENSE', 'lib/**/*.rb')
  rdoc.title = 'R18n for Rails Documentation'
  rdoc.rdoc_dir = 'doc'
  rdoc.options << '-c utf-8'
  rdoc.options << '--all'
end

